---
title: "Visualisation"
author: "Brian M Schilder"
date: "Vignette updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i>"
output:
  rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{visualisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE, message=FALSE}
library(dplyr)
library(tidygraph)
library(monarchr)
library(ggplot2)

options(width = 300)
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, fig.width = 10, message = FALSE, warning = FALSE)
```


```{r}
palette <- c("#2c8c9a","#79e4e7","#a7ecf3","#fafafa","white")
```


## Create network

```{r}
immune <- monarch_search("immune system", 
												 category = "biolink:Disease")|>
	expand(predicates = "biolink:subclass_of") |>
	expand(predicates = "biolink:has_phenotype",
         categories = "biolink:PhenotypicFeature") |>
	expand(categories = "biolink:Gene")
	
	
monarch <- monarch_engine()
g <- monarch |> 
	fetch_nodes("biolink:Disease" %in_list% category ) |>
	expand(categories = "biolink:Disease") |>
	expand(predicates = "biolink:has_phenotype",
         categories = "biolink:PhenotypicFeature") |>
	expand(categories = "biolink:Gene")
g 
 
immune|>
	activate(nodes)|> 
	filter(pcategory %in% c("biolink:Disease", "biolink:PhenotypicFeature")) |>
	# filter(pcategory %in% c())
	# sample_n(1000) |>
	activate(edges)|>
  filter(tidygraph::edge_is_between(which(nodes(g)$pcategory=="biolink:Disease"),
  																	which(nodes(g)$pcategory=="biolink:Disease"), 
  																	ignore_dir=TRUE)) |>
	activate(nodes) |>
	filter(!node_is_isolated()) |>
	plot(layout="fr")


lapply(edges(g), function(x)sum(!is.na(unlist(x)))/length(unlist(x)))
as.list(table(edges(g)$knowledge_level,useNA = "always"))
hist(as.numeric(na.omit(edges(g)$has_percentage)))
# knowledge_level * 
# frequency_qualifier **
# negated ?
# has_total
# has_quotient
# has_count
# has_percentage *
# has_evidence *
# has_percentage
# onset_qualifier
# publications **
```

## Default

```{r}
plot(g)
```

## ggraph

```{r}
library(ggraph)
plot_graph <- function(g, layout = "fr", ...){
	g|>
	  ggraph(layout = layout) +
	  # geom_edge_density() +
		geom_edge_bundle_force2(
			# aes(colour = after_stat(index)),
														alpha=.5,
													  threshold = 0.4) +
	geom_edge_link(aes(linetype = predicate,
										 # color=edge_rank_eulerian()
										 ),
								 alpha=.5,
								 arrow=arrow(length = unit(0.2,"in"),
								 						 type = "closed")) + 
	geom_node_point(aes(color=pcategory, 
											shape=pcategory,
											size = centrality_harmonic()
											)
									) +
	geom_node_label(aes(label=ifelse(pcategory=="biolink:Gene",
																	 name, 
																	 stringr::str_wrap(paste0(name,"\n","(",id,")"),30)
																	 ), 
											fill=pcategory),
									show.legend = FALSE,
									alpha=.75,
									repel = TRUE) +
	facet_nodes(~provided_by, scales = "free") +
	theme_void()
}

plot_graph(immune, layout = "fr") 
```


## `plotly`

```{r}
# 
# library(plotly)
# p <- KGExplorer::graph_to_plotly(g)
# network <- plot_ly(data = p$vertices,
# 									 x = ~x, y = ~y, z = ~z,
# 									 mode = "markers", 
# 									 text = ~name, 
# 									 hoverinfo = "text")
# axis <- list(title = "", showgrid = FALSE, showticklabels = FALSE, zeroline = FALSE)
# fig <- layout(
#   network,
#   shapes = edge_shapes,
#   xaxis = axis,
#   yaxis = axis
# )
# network


```


## visNetwork

```{r}
library(visNetwork)
visIgraph(g) |>
	visNodes()
```


## node2vec

```{r}
library(node2vec)

df <- igraph::as_data_frame(g)

# emb <- node2vecR(df[,c("from","to")],
# 								 p=2,q=1,
# 								 num_walks=5,
# 								 walk_length=5,
# 								 dim=128)
# X <- as.matrix(g)
X <- igraph::similarity(g, method="dice")
rownames(X) <- colnames(X) <- igraph::V(g)$name
umap_res <- umap::umap(X)
umap_dt <- merge(
	nodes(g),
	cbind(name=rownames(umap_res$layout),
				data.frame(umap_res$layout) |>`colnames<-`(c("umap1","umap2"))
		),
	by="name"
)|>data.table::data.table()

ggplot2::ggplot(umap_dt, aes(x=umap1, y=umap2, color=pcategory)) +
	geom_point(alpha=.1)+
	geom_label(data=umap_dt[pcategory!="biolink:Gene"],
						aes(label=name), size=2) +
	theme_bw()


g|>
	  ggraph(layout = umap_res$layout) +
	 # geom_edge_density() +
		geom_edge_bundle_force2(
			# aes(colour = after_stat(index)),
														alpha=.5,
													  threshold = 0.4) +
	geom_edge_link(aes(linetype = predicate,
										 ),
								 alpha=.5,
								 arrow=arrow(length = unit(0.2,"in"),
								 						 type = "closed")) + 
	geom_node_point(aes(color=pcategory, 
											shape=pcategory,
											size = centrality_harmonic()
											)
									) 
```

## Compare ontological vs. phenotypic vs. genetic similarity

```{r}
# filename <- system.file("extdata", "eds_marfan_kg.tar.gz", package = "monarchr")
# Gd <- file_engine(filename) |>
# 	fetch_nodes(pcategory=="biolink:Disease")|>
# 	expand(categories = "biolink:Disease")
Gd_all <- monarch_engine() |>
  	fetch_nodes("biolink:Disease" %in_list% category ) |>
		expand(categories = "biolink:Disease")


Gd <- monarch_engine() |>
  	fetch_nodes(query_ids = c("MONDO:0001982")) |>
		expand(categories = "biolink:Disease")
ids <- nodes(Gd)$id
Sd <- graph_semsim(Gd, return_matrix = TRUE)[ids,ids]
Sd_all <- graph_semsim(Gd_all, return_matrix = TRUE)[ids,ids]
Gd_0 <- Gd |>
		activate(edges)|>
		filter(predicate != "biolink:subclass_of")


Gp <- Gd |>
          expand_n(categories = "biolink:PhenotypicFeature",
          				 return_each = TRUE,
          				 n=3)

Gg <- Gd |>
				expand_n(categories = "biolink:Gene",
								 return_each = TRUE,
								 n=3)

Gg2 <- Gd |>
          expand_n(predicates = list("biolink:causes","biolink:interacts_with","biolink:interacts_with"),
                   categories = "biolink:Gene",
          				 return_each = TRUE,
          				 n=3)

Gpg <- Gd |>
 				activate(edges)|>
				filter(predicate != "biolink:subclass_of")|>
          expand(predicates = "biolink:has_phenotype",
                 categories = "biolink:PhenotypicFeature")|>
					expand(categories = "biolink:Gene")

prep_ss <- function(g,ids, method="dice"){
	if(is(g,"igraph")){
		list(iteration0=graph_semsim(g,return_matrix=TRUE,method=method)[ids,ids]|>as.numeric())
	}else{
		lapply(g,function(x)graph_semsim(x,return_matrix=TRUE,method=method)[ids,ids]|>as.numeric())	
	}
}

X <- do.call(cbind,c(
						list(Disease.all=as.numeric(Sd_all)),
					 	Disease_subset=prep_ss(Gd,ids), 
					 	Phenotype=prep_ss(Gp,ids), 
						 Gene=prep_ss(Gg,ids),
						 Gene_causal=prep_ss(Gg2,ids),
						 Phenotype_Gene=prep_ss(Gpg,ids)
					 )
					 )
heatmaply::heatmaply(cor(X))

X <- layout_umap(Gd)
Gd <- graph_centrality(Gd)
plot(Gd, layout=X, node_size=centrality)

```


